Controllers/LeaveTypesController.cs
using AutoMapper;
using Leave_Management.Contracts;
using Leave_Management.Data;
using Leave_Management.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Leave_Management.Controllers
{
    [Authorize(Roles = "Administrator, Manager")]
    public class LeaveTypesController : Controller
    {
        private readonly IUnitOfWork _uow;
        private readonly IMapper _mapper;

        public LeaveTypesController(IUnitOfWork uow, IMapper mapper)
        {
            _uow = uow;
            _mapper = mapper;
        }

        #region API Calls

        public IActionResult GetAll()
        {
            var leaveType = _uow.LeaveType.GetAll().ToList();
            var model = _mapper.Map<List<LeaveType>, List<LeaveTypeVM>>(leaveType);
            return Json(new { data = model });
        }

        // GET: LeaveType/Delete/5
        [HttpDelete]
        public async Task<IActionResult> Delete(int id)
        {
            var dataLeaveType = await _uow.LeaveType.Get(id);
            if (dataLeaveType == null)
                return Json(new { success = false, message = "Data Not Found!" });
            _uow.LeaveType.Delete(dataLeaveType);
            _uow.Save();
            return Json(new { success = true, message = "Delete Operation Successfully" });
        }
        #endregion

        // GET: LeaveType
        public ActionResult Index()
        {
            return View();
        }

        // GET: LeaveType/Details/5
        public async Task<IActionResult> Details(int id)
        {
            var model = await _uow.LeaveType.GetFirstOrDefault(u => u.Id == id);
            if (model == null)
            {
                return NotFound();
            }

            var models = _mapper.Map<LeaveTypeVM>(model);

            return View(models);
        }

        // GET: LeaveType
        public async Task<IActionResult> Create(int? id)
        {
            if (id == null)
            {
                //Create
                return View(new LeaveTypeVM());
            }
            //Update

            var model = await _uow.LeaveType.GetFirstOrDefault(u => u.Id == id);
            var leaveTypeVm = _mapper.Map<LeaveTypeVM>(model);

            if (leaveTypeVm == null)
            {
                return NotFound();
            }
            return View(leaveTypeVm);
        }

        // POST: LeaveType/Create/Update
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(LeaveTypeVM model)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View(model);
                }

                if (model.Id == 0) //Create
                {
                    TempData["result"] = "Create";
                    var leaveType = _mapper.Map<LeaveType>(model);
                    leaveType.DateCreated = DateTime.Now;
                    _uow.LeaveType.Create(leaveType);
                }
                else // Update
                {
                    TempData["result"] = "Update";
                    var leaveType = _mapper.Map<LeaveType>(model);
                    _uow.LeaveType.Update(leaveType);
                }
                _uow.Save();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View(model);
            }
        }


    //     public IActionResult DownloadLeaveTypes()
    //{
    //    var leaveTypes = _uow.LeaveType.GetAll(); // Retrieve all leave types from the database

    //    // Create a new Excel package
    //    using (var package = new ExcelPackage())
    //    {
    //        var worksheet = package.Workbook.Worksheets.Add("Leave Types"); // Create a worksheet

    //        // Add column headers
    //        worksheet.Cells["A1"].Value = "Leave Type Name";
    //        worksheet.Cells["B1"].Value = "Description";
    //        worksheet.Cells["C1"].Value = "Number of Days";

    //        // Populate data rows
    //        int row = 2;
    //        foreach (var leaveType in leaveTypes)
    //        {
    //            worksheet.Cells["A" + row].Value = leaveType.Name;
    //            zzworksheet.Cells["B" + row].Value = leaveType.Description;
    //            worksheet.Cells["C" + row].Value = leaveType.NumberOfDays;
    //            row++;
    //        }

    //        // Convert the Excel package to a byte array
    //        byte[] excelData = package.GetAsByteArray();

    //        // Return the Excel file as a downloadable file
    //        return File(excelData, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "LeaveTypes.xlsx");
    //    }
    //}






    }
}

Controllers/UserRolesController.cs
using Leave_Management.Data;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace Leave_Management.Controllers
{
    public class UserRolesController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly RoleManager<UserRole> _roleManager;

        public UserRolesController(ApplicationDbContext context, RoleManager<UserRole> roleManager)
        {
            _context = context;
            _roleManager = roleManager;
        }

        // GET: UserRoles
        public async Task<IActionResult> Index()
        {
            return View(await _context.Roles.ToListAsync());
        }

        // GET: UserRoles/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null || _context.Roles == null)
            {
                return NotFound();
            }

            var userRole = await _context.Roles
                .FirstOrDefaultAsync(m => m.Id == id);
            if (userRole == null)
            {
                return NotFound();
            }

            return View(userRole);
        }

        // GET: UserRoles/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: UserRoles/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name")] UserRole userRole)
        {
            if (string.IsNullOrWhiteSpace(userRole.Name))
            {
                ModelState.AddModelError("Name", "Role name is required");
            }


            if (ModelState.IsValid)
            {
                var normalizedRoleName = userRole.Name?.ToUpper() ?? string.Empty;

                var existingRole = await _context.Roles
                                                 .FirstOrDefaultAsync(r => r.NormalizedName == normalizedRoleName);

                if (existingRole != null)
                {
                    ModelState.AddModelError("Name", "Role name already exists");
                }

                if (ModelState.IsValid)
                {
                    userRole.Id = Guid.NewGuid().ToString();
                    userRole.NormalizedName = normalizedRoleName;
                    userRole.ConcurrencyStamp = Guid.NewGuid().ToString();

                    _context.Add(userRole);
                    await _context.SaveChangesAsync();

                    return RedirectToAction(nameof(Index));
                }
            }

            return View(userRole);
        }

        // GET: UserRoles/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null || _context.Roles == null)
            {
                return NotFound();
            }

            var userRole = await _context.Roles.FindAsync(id);
            if (userRole == null)
            {
                return NotFound();
            }
            return View(userRole);
        }

        // POST: UserRoles/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Name, Id, NormalizedName, ConcurrencyStamp")] UserRole role)
        {
            if (id != role.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    // Retrieve the existing role from the database
                    var existingRole = await _roleManager.FindByIdAsync(id);

                    if (existingRole == null)
                    {
                        return NotFound();
                    }

                    // Update the properties of the existingRole with the values from role
                    existingRole.Name = role.Name;

                    await _roleManager.UpdateAsync(existingRole);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!await _roleManager.RoleExistsAsync(role.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(role);
        }


        // GET: UserRoles/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null || _context.Roles == null)
            {
                return NotFound();
            }

            var userRole = await _context.Roles
                .FirstOrDefaultAsync(m => m.Id == id);
            if (userRole == null)
            {
                return NotFound();
            }

            return View(userRole);
        }

        // POST: UserRoles/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            if (_context.Roles == null)
            {
                return Problem("Entity set 'ApplicationDbContext.UserRole'  is null.");
            }
            var userRole = await _context.Roles.FindAsync(id);
            if (userRole != null)
            {
                _context.Roles.Remove(userRole);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UserRoleExists(string id)
        {
            return _context.Roles.Any(e => e.Id == id);
        }
    }
}

Views/Shared/_AdminLTE.cshtml
@using Microsoft.AspNetCore.Identity
@using Leave_Management.Data
@inject SignInManager<Employee> SignInManager
@inject UserManager<Employee> UserManager

@{
    var currentController = ViewContext.RouteData.Values.ContainsKey("controller")
       ? ViewContext.RouteData.Values["controller"].ToString()
       : string.Empty;

    var currentAction = ViewContext.RouteData.Values.ContainsKey("action")
        ? ViewContext.RouteData.Values["action"].ToString()
        : string.Empty;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Core Leave Management</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" type="text/css" href="~/css/jquery-ui.min.css" />
    <link rel="stylesheet" type="text/css" href="~/css/dataTables.min.css" />
    <link rel="stylesheet" type="text/css" href="~/css/toastr.min.css" />
    <link rel="stylesheet" type="text/css" href="~/css/font-awesome.css" />


    <link rel="stylesheet" href="~/css/adminlte.min.css">
</head>

<body class="@(SignInManager.IsSignedIn(User) ? "" : "sidebar-collapse") ">
    <div class="wrapper">

        <!-- Navbar -->
        <nav class="main-header navbar navbar-expand navbar-white navbar-light">
            <!-- Left navbar links -->
            <ul class="navbar-nav">
                @if (SignInManager.IsSignedIn(User))
                {

                    <li class="nav-item">
                        <a class="nav-link" data-widget="pushmenu" href="#"><i class="fas fa-bars"></i></a>
                    </li>
                }
                else
                {
                <li class="nav-item ">
                        <a href="/Home/Index" class="nav-link"><h3>Leave Management</h3></a>
                </li>
                    
                }
            </ul>
        </nav>
        <!-- /.navbar -->
        <!-- Main Sidebar Container -->

        <aside class="main-sidebar sidebar-dark-primary elevation-4">
            <!-- Brand Logo -->
            <a href="#" class="brand-link">
                @*<img src="dist/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3"
                style="opacity: .8">*@
                <span class="brand-text font-weight-light">Leave Management</span>
            </a>

            <!-- Sidebar -->
            <div class="sidebar">
                <!-- Sidebar user panel (optional) -->
                <partial name="_LoginPartial" />
                <hr />

                <!-- Sidebar Menu -->
                <nav class="mt-2">
                    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                        <!-- Add icons to the links using the .nav-icon class
                        with font-awesome or any other icon font library -->
                        @if (SignInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                    <a asp-area="" asp-controller="Home" asp-action="Index" class="nav-link @(Url.IsActive("Home","Index",currentController,currentAction))">
                                    <i class="nav-icon fas fa-home"></i>
                                    <p>
                                        Home
                                    </p>
                                </a>
                            </li>
                        }

                        @if (SignInManager.IsSignedIn(User))
                        {
                           @*  if (User.IsInRole("Employee")) *@
                            {
                                <li class="nav-item">
                                        <a asp-area="" asp-controller="LeaveRequests" asp-action="Upsert" class="nav-link @(Url.IsActive("LeaveRequests","Upsert",currentController,currentAction))">
                                        <i class="nav-icon fas fa-pen-alt"></i>
                                        <p>
                                            Apply For Leave
                                        </p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                        <a asp-area="" asp-controller="LeaveRequests" asp-action="MyLeave" class="nav-link @(Url.IsActive("LeaveRequests","MyLeave",currentController,currentAction))">
                                        <i class="nav-icon fas fa-book-open"></i>
                                        <p>
                                            My Leave
                                        </p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a asp-area="" asp-controller="EventCalendar" asp-action="Index" class="nav-link @(Url.IsActive("EventCalendar","Index",currentController,currentAction))">
                                        <i class="nav-icon fas fa-book-open"></i>
                                        <p>
                                            Add Calendar Events
                                        </p>
                                    </a>
                                </li>
                            }
                        }
                        @if (SignInManager.IsSignedIn(User))
                        {
                            if (User.IsInRole("Administrator") || (User.IsInRole("Manager")))
                            {
                                <li class="nav-item has-treeview menu-open">
                                    <a href="#" class="nav-link">
                                        <i class="nav-icon fas fa-tachometer-alt"></i>
                                        <p>
                                            Manage
                                            <i class="right fas fa-angle-down"></i>
                                        </p>
                                    </a>
                                    <ul class="nav nav-treeview">
                                        <li class="nav-item">
                                                <a asp-area="" asp-controller="LeaveTypes" asp-action="Index" class="nav-link @(Url.IsActive("LeaveTypes","Index",currentController,currentAction))">
                                                <i class="fas fa-list nav-icon"></i>
                                                <p>Leave Types</p>
                                            </a>
                                        </li>
                                        
                                        <li class="nav-item">
                                                <a asp-area="" asp-controller="LeaveAllocations" asp-action="Index" class="nav-link @(Url.IsActive("LeaveAllocations","Index",currentController,currentAction))">
                                                <i class="fas fa-user-plus nav-icon"></i>
                                                <p>Leave Allocations</p>
                                            </a>
                                        </li>
                                        <li class="nav-item">
                                                <a asp-area="" asp-controller="LeaveRequests" asp-action="Index" class="nav-link @(Url.IsActive("LeaveRequests","Index",currentController,currentAction))">
                                                <i class="fas fa-cogs nav-icon"></i>
                                                <p>Leave Requests</p>
                                            </a>
                                        </li>
                                        
                                        <li class="nav-item">
                                                <a asp-area="" asp-controller="LeaveAllocations" asp-action="ListEmployee" class="nav-link @(Url.IsActive("LeaveAllocations","ListEmployee",currentController,currentAction))">
                                                <i class="fas fa-users nav-icon"></i>
                                                <p>Employees</p>
                                            </a>
                                        </li>
                                        
                                        <li class="nav-item">
                                            <a asp-area="" asp-controller="LeaveAllocations" asp-action="AssignManager" class="nav-link @(Url.IsActive("LeaveAllocations","AssignManager",currentController,currentAction))">
                                                <i class="fas fa-user-friends nav-icon"></i>
                                                <p>Assign Manager</p>
                                            </a>
                                        </li>
                                        <li class="nav-item">
                                            <a asp-area="" asp-controller="UserRoles" asp-action="Index" class="nav-link @(Url.IsActive("UserRoles","Index",currentController,currentAction))">
                                                <i class="fas fa-user-friends nav-icon"></i>
                                                <p>Role</p>
                                            </a>
                                        </li>
                                        <li class="nav-item">
                                            <a asp-controller="LeaveAllocations" asp-action="EmployeeRoles" class="nav-link @(Url.IsActive("LeaveAllocations","EmployeeRoles",currentController,currentAction))">
                                                <i class="fas fa-user-shield"></i>
                                                <p>Change User Role</p>
                                            </a>
                                        </li>

                                    </ul>
                                </li>
                            }
                        }
                    </ul>
                </nav>
                <!-- /.sidebar-menu -->
            </div>
            <!-- /.sidebar -->
        </aside>


        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <div class="content-header">
                <div class="container-fluid">

                </div><!-- /.container-fluid -->
            </div>
            <!-- /.content-header -->
            <!-- Main content -->
            <div class="content">
                <div class="container-fluid">
                    @RenderBody()
                    <!-- /.row -->
                </div><!-- /.container-fluid -->
            </div>
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->
        <!-- Control Sidebar -->
        <aside class="control-sidebar control-sidebar-dark">
            <!-- Control sidebar content goes here -->
            <div class="p-3">
                <h5>Title</h5>
                <p>Sidebar content</p>
            </div>
        </aside>
        <!-- /.control-sidebar -->
        <!-- Main Footer -->
         </div>    <!-- ./wrapper -->
    <!-- jQuery -->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/jquery-ui.min.js"></script>
    <script src="~/js/all.min.js"></script>
    <script src="~/js/dataTable.min.js"></script>
    <script src="~/js/toastr.min.js"></script>
    <script src="~/js/sweetalert.js"></script>
    <!-- AdminLTE App -->
    <script src="~/js/adminlte.js"></script>

    @RenderSection("Scripts", required: false)

</body>
</html>

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Hosting
@using Microsoft.AspNetCore.Mvc.ViewEngines
@inject IWebHostEnvironment Environment
@inject ICompositeViewEngine Engine
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Leave Management</title>
    <link rel="stylesheet" href="~/Identity/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/Identity/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-light navbar-toggleable-sm bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" href="~/">Leave Management</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    @{
                        var result = Engine.FindView(ViewContext, "_LoginPartial", isMainPage: false);
                    }
                    @if (result.Success)
                    {
                        await Html.RenderPartialAsync("_LoginPartial");
                    }
                    else
                    {
                        throw new InvalidOperationException("The default Identity UI layout requires a partial view '_LoginPartial' " +
                            "usually located at '/Pages/_LoginPartial' or at '/Views/Shared/_LoginPartial' to work. Based on your configuration " +
                            $"we have looked at it in the following locations: {System.Environment.NewLine}{string.Join(System.Environment.NewLine, result.SearchedLocations)}.");
                    }
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <footer class="footer border-top text-muted">
        <div class="container">
            &copy; 2024 - Leave Management - <a asp-area="" asp-page="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/Identity/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/Identity/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/Identity/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>