Controllers/LeaveRequestsController.cs
using AutoMapper;
using Leave_Management.Contracts;
using Leave_Management.Data;
using Leave_Management.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Leave_Management.Controllers
{





    [Authorize]

    public class LeaveRequestsController : Controller
    {
        private readonly IUnitOfWork _uow;
        private readonly UserManager<Employee> _userManager;
        private readonly IMapper _mapper;

        public LeaveRequestsController(IUnitOfWork uow, UserManager<Employee> userManager, IMapper mapper)
        {
            _uow = uow;
            _userManager = userManager;
            _mapper = mapper;
        }

        // GET: LeaveRequests
        [Authorize(Roles = "Administrator, Manager")]
        public ActionResult Index()
        {
            var leaveRequest = _uow.LeaveRequest.GetAll(includeProperties: "LeaveType",
                includeProperty: "RequestingEmployee", includeProperte: "ApprovedBy");
            var leaveRequestModel = _mapper.Map<List<LeaveRequestVm>>(leaveRequest);
            var cancelled = leaveRequest.Count(x => x.Cancelled == true);
            var model = new AdminLeaveRequestVm
            {
                TotalRequest = leaveRequestModel.Count,
                ApprovedRequest = leaveRequestModel.Count(x => x.Approved == true),
                PendingRequest = leaveRequestModel.Count(x => x.Approved == null) - cancelled,
                RejectedRequest = leaveRequestModel.Count(x => x.Approved == false),
                LeaveRequest = leaveRequestModel
            };
            return View(model);
        }
        public async Task<ActionResult> Details(int id)
        {
            var leaveRequest = await _uow.LeaveRequest.GetAllWithThreeEntity((x => x.Id == id), includeProperties: "ApprovedBy", includeProperty: "RequestingEmployee", includeProperte: "LeaveType");
            var model = _mapper.Map<LeaveRequestVm>(leaveRequest);
            return View(model);
        }






        //[HttpGet]
        //public async Task<IActionResult> RejectionMessage(int id)
        //{
        //    var leaveRequest = await _uow.LeaveRequest.Get(id);
        //    var model = _mapper.Map<LeaveRequestVm>(leaveRequest);
        //    return View(model);
        //}

        //[HttpPost]
        //public async Task<IActionResult> RejectionMessage(LeaveRequestVm model)
        //{
        //    if (!ModelState.IsValid)
        //    {
        //        return View(model);
        //    }

        //    var leaveRequest = await _uow.LeaveRequest.Get(model.Id);
        //    leaveRequest.RejectionMessage = model.RejectionMessage;

        //    _uow.LeaveRequest.Update(leaveRequest);
        //    _uow.Save(); // Assuming SaveAsync is an asynchronous save method

        //    return RedirectToAction("Index", "LeaveRequests");
        //}





        public async Task<ActionResult> ApproveRequest(int id)
        {
            try
            {
                var user = await _userManager.GetUserAsync(User);
                var leaveRequest = await _uow.LeaveRequest.Get(id);
                if (leaveRequest.RequestingEmployeeId == user.Id)
                {
                    TempData["ErrorMessageApprove"] = "You cannot approve your own leave request!";
                    return RedirectToAction(nameof(Details), new { id = id });
                }
                var employeeId = leaveRequest.RequestingEmployeeId;
                var leaveTypeId = leaveRequest.LeaveTypeId;
                var allocation = await _uow.LeaveAllocation.GetAllWithTwoEntity((x =>
                    x.EmployeeId == employeeId && x.Period == DateTime.Now.Year &&
                    x.LeaveType.Id == leaveTypeId));
                int daysRequested = (int)(leaveRequest.EndDate - leaveRequest.StartDate).TotalDays + 1;
                for (int i = 0; i < daysRequested; i++)
                {
                    var currentDate = leaveRequest.StartDate.AddDays(i);
                    if (currentDate.DayOfWeek == DayOfWeek.Saturday || currentDate.DayOfWeek == DayOfWeek.Sunday)
                    {
                        daysRequested--;
                    }
                }
                //allocation.NumberOfDays -= daysRequested;
                allocation.NumberOfDays = allocation.NumberOfDays - daysRequested;

                leaveRequest.Approved = true;
                leaveRequest.ApprovedById = user.Id;
                leaveRequest.DateActioned = DateTime.Now;

                _uow.LeaveRequest.Update(leaveRequest);
                _uow.LeaveAllocation.Update(allocation);
                _uow.Save();
                return RedirectToAction(nameof(Index));

            }
            catch (Exception ex)
            {
                return RedirectToAction(nameof(Index));
            }
        }

        public async Task<ActionResult> RejectRequest(int id, string rejectionMessage)
        {
            try
            {
                //if(rejectionMessage == null)
                //{
                //    TempData["EmptyRejectionMessage"] = "Rejection message cannot be empty!";
                //    return RedirectToAction(nameof(Details), new {id = id});
                //}
                var user = await _userManager.GetUserAsync(User);

                var leaveRequest = await _uow.LeaveRequest.Get(id);
                if(leaveRequest.RequestingEmployeeId != user.Id)
                {
                    leaveRequest.Approved = false;
                    leaveRequest.ApprovedById = user.Id;
                    leaveRequest.DateActioned = DateTime.Now;
                    leaveRequest.RejectionMessage = rejectionMessage; // Set rejection message

                    _uow.LeaveRequest.Update(leaveRequest);
                    _uow.Save(); // Assuming SaveAsync is an asynchronous save method

                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    TempData["ErrorMessageReject"] = "You cannot reject your own leave request!";
                    return RedirectToAction(nameof(Details), new {id = id});
                }
               
            }
            catch (Exception ex)
            {
                // Handle exception
                return RedirectToAction(nameof(Index));
            }
        }



        public ActionResult MyLeave()
        {
            var employee = _userManager.GetUserAsync(User).Result;
            if (employee == null)
            {
                return View();
            }

            var employeeId = employee.Id;

            // Retrieve all approved leave requests for the employee
            var approvedRequests = _uow.LeaveRequest.GetAll(x => x.RequestingEmployeeId == employeeId && x.Approved == true);

            // Calculate total approved leave days
            var totalApprovedLeave = approvedRequests.Sum(x => (x.EndDate - x.StartDate).Days + 1);



            // Rest of your code
            var employeeAllocation = _uow.LeaveAllocation.GetAll(includeProperties: "LeaveType")
                .Where(x => x.EmployeeId == employeeId && x.Period == DateTime.Now.Year)
                .ToList();


            var employeeRequest = _uow.LeaveRequest.GetAll((x => x.RequestingEmployeeId == employeeId),
                includeProperties: "LeaveType", includeProperty: "RequestingEmployee", includeProperte: "ApprovedBy");
            var employeeAllocationModel = _mapper.Map<List<LeaveAllocationVm>>(employeeAllocation);
            var employeeRequestModel = _mapper.Map<List<LeaveRequestVm>>(employeeRequest);

            var model = new EmployeeLeaveRequestVm
            {
                LeaveAllocations = employeeAllocationModel,
                LeaveRequests = employeeRequestModel,
                TotalApprovedLeave = totalApprovedLeave // Add total approved leave to the model
            };

            return View(model);
        }

        public ActionResult MyLeaveGet()
        {
            var employee = _userManager.GetUserAsync(User).Result;
            if(employee == null)
            {
                return NotFound();
            }
            var employeeId = employee.Id;

            // Retrieve all approved leave requests for the employee
            var approvedRequests = _uow.LeaveRequest.GetAll(x => x.RequestingEmployeeId == employeeId && x.Approved == true);

            // Calculate total approved leave days

            var RejectRequests = _uow.LeaveRequest.GetAll(x => x.RequestingEmployeeId == employeeId && x.Approved == false);
            var PendingRequests = _uow.LeaveRequest.GetAll(x => x.RequestingEmployeeId == employeeId && x.Approved == null && x.Cancelled == false);

            // Calculate total approved leave days
            var totalApprovedLeave = approvedRequests.Sum(x => x.TotalDays);
            var totalRejectLeave = RejectRequests.Count();
            var totalPendingLeave = PendingRequests.Count();

            // Rest of your code
            var employeeAllocation = _uow.LeaveAllocation.GetAll(includeProperties: "LeaveType")
                .Where(x => x.EmployeeId == employeeId && x.Period == DateTime.Now.Year)
                .ToList();
            var employeeRequest = _uow.LeaveRequest.GetAll((x => x.RequestingEmployeeId == employeeId),
                includeProperties: "LeaveType", includeProperty: "RequestingEmployee", includeProperte: "ApprovedBy");
            var employeeAllocationModel = _mapper.Map<List<LeaveAllocationVm>>(employeeAllocation);
            var employeeRequestModel = _mapper.Map<List<LeaveRequestVm>>(employeeRequest);

            var model = new EmployeeLeaveRequestVm
            {
                LeaveAllocations = employeeAllocationModel,

Views/LeaveRequests/Details.cshtml
@model Leave_Management.Models.LeaveRequestVm

@{
    ViewData["Title"] = "Details";
}


@if (TempData["ErrorMessageReject"] != null)
{
    <div class="alert alert-danger" role="alert">Cannot Reject your own leave request!</div>
}

@if(TempData["ErrorMessageApprove"] != null)
{
    <div class="alert alert-danger" role="alert">Cannot Approve your own leave request!</div>
}
@if (TempData["EmptyRejectionMessage"] != null)
{
    <div class="alert alert-warning" role="alert">Rejection reason cannot be empty!</div>
}

@if (Model.Approved == null)
{
    <div class="alert alert-warning" role="alert">
        <h4 class="alert-heading">Pending Approval</h4>
        <p>
            <strong>@Html.DisplayNameFor(model => model.RequestingEmployeeId):</strong>  @Model.RequestingEmployee.Firstname @Model.RequestingEmployee.Lastname 's Leave Request <br />
        </p>
        <hr />
        <p>
            @Html.DisplayNameFor(model => model.DateRequested) - @Html.DisplayFor(model => model.DateRequested)
        </p>
    </div>
}
else if (Model.Approved == true)
{
    <div class="alert alert-success" role="alert">
        <h4 class="alert-heading">Approved by @Model.ApprovedBy.Firstname @Model.ApprovedBy.Lastname</h4>
        <p>
            <strong>@Html.DisplayNameFor(model => model.RequestingEmployeeId):</strong> @Model.RequestingEmployee.Firstname @Model.RequestingEmployee.Lastname  <br />
        </p>
        <hr />
        <p>
            @Html.DisplayNameFor(model => model.DateRequested) - @Html.DisplayFor(model => model.DateRequested)
        </p>
    </div>
}
else
{
    <div class="alert alert-danger" role="alert">
        <h4 class="alert-heading">Rejected by @Model.ApprovedBy.Firstname @Model.ApprovedBy.Lastname</h4>
        <p>
            <strong>@Html.DisplayNameFor(model => model.RequestingEmployeeId):</strong> @Model.RequestingEmployee.Firstname @Model.RequestingEmployee.Lastname <br />
        </p>
        <hr />
        <p>
            @Html.DisplayNameFor(model => model.DateRequested) - @Html.DisplayFor(model => model.DateRequested)
        </p>
    </div>
}
<div>

    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.StartDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.EndDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.LeaveType)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.LeaveType.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.RequestComments)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.RequestComments)
        </dd>
    </dl>
</div>
<div>
    @if (Model.Approved == null)
    {
        <a class="btn btn-success" asp-action="ApproveRequest" asp-route-id="@Model.Id">
            <i class="fas fa-check"></i> Approve
        </a>
        <a class="btn btn-danger" id="rejectButton" data-toggle="modal" data-target="#rejectModal">
            <i class="fas fa-remove"></i> Reject
        </a>
    }





    <a class="btn btn-outline-secondary" asp-action="Index">
        <i class="fa fa-arrow-left"></i> Back to List
    </a>
</div>


<!-- Button to trigger modal -->

<div class="modal" id="myModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <!-- Modal Header -->
            <div class="modal-header">
                <h5 class="modal-title">Enter Rejection Reason</h5>
                
            </div>

            <!-- Modal Body -->
            <div class="modal-body">
                <input type="text" class="form-control" id="rejectionReasonInput" placeholder="Enter reason...">
                <div class="invalid-feedback">Please enter rejection reason.</div>
            </div>

            <!-- Modal Footer -->
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal" id="closeModal">Close</button>
                <button type="button" class="btn btn-primary" id="submitRejection">Submit</button>
            </div>
        </div>
    </div>
</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js" integrity="sha512-qFOQ9YFAeGj1gDOuUD61g3D+tLDv3u1ECYWqT82WQoaWrOhAY+5mRMTTVsQdWutbA5FORCnkEPEgU0OF8IzGvA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
@* <script>
    document.getElementById("rejectButton").addEventListener("click", function () {
        let rejectionMessage = prompt("Enter rejection reason: ");
        window.location.href = '/LeaveRequests/RejectRequest?id=@Model.Id&rejectionMessage=' + encodeURIComponent(rejectionMessage);

    });
</script> *@

<script>
    // Get references to the modal and its elements
    let modal = document.getElementById("myModal");
    let closeButton = document.getElementById("closeModal");
    let submitButton = document.getElementById("submitRejection");
    let rejectionInput = document.getElementById("rejectionReasonInput");

    // Function to validate rejection reason
    function validateRejection() {
        if (rejectionInput.value.trim() === "") {
            rejectionInput.classList.add("is-invalid");
            return false;
        } else {
            rejectionInput.classList.remove("is-invalid");
            return true;
        }
    }

    // Show modal when "Reject" button is clicked
    document.getElementById("rejectButton").addEventListener("click", function () {
        modal.style.display = "block";
    });

    // Close modal when close button is clicked
    closeButton.addEventListener("click", function () {
        modal.style.display = "none";
    });

    // Submit rejection when submit button is clicked
    submitButton.addEventListener("click", function () {
        if (validateRejection()) {
            let rejectionMessage = rejectionInput.value.trim();
            window.location.href = '/LeaveRequests/RejectRequest?id=@Model.Id&rejectionMessage=' + encodeURIComponent(rejectionMessage);
            modal.style.display = "none"; // Close the modal
        }
    });

    // Close modal if the user clicks outside of it
    window.addEventListener("click", function (event) {
        if (event.target === modal) {
            modal.style.display = "none";
        }
    });

    // Close modal when ESC key is pressed
    window.addEventListener("keydown", function (event) {
        if (event.key === "Escape" && modal.style.display === "block") {
            modal.style.display = "none";
        }
    });

</script>

Views/LeaveRequests/Index.cshtml
@model AdminLeaveRequestVm

@{
    ViewData["Title"] = "Index";
}





<button id="exportButton" class="btn btn-primary">
    <i class="fas fa-download"></i> Export to CSV
</button>



<hr />
<h1>Leave Request Log</h1>
<hr />
<table id="mytable" class="table">
    <!-- Table headers -->
    <thead>
        <tr>
            <th>Employee Name</th>
            <th>Total Days</th>
            <th>Start Date</th>
            <th>End Date</th>
            <th>Leave Type</th>
            <th>Date Requested</th>
            <th>Approval Status</th>
            <th></th>
        </tr>
    </thead>
    <!-- Table body -->
    <tbody>
        @foreach (var item in Model.LeaveRequest)
        {
            <!-- Table rows -->
            <tr>
                <td>@Html.DisplayFor(modelItem => item.RequestingEmployee.Firstname) @Html.DisplayFor(modelItem => item.RequestingEmployee.Lastname)</td>
                <td>@Html.DisplayFor(modelItem => item.TotalDays)</td>
                <td>@Html.DisplayFor(modelItem => item.StartDate)</td>
                <td>@Html.DisplayFor(modelItem => item.EndDate)</td>
                <td>@Html.DisplayFor(modelItem => item.LeaveType.Name)</td>
                <td>@Html.DisplayFor(modelItem => item.DateRequested)</td>
                <td>
                    @if (item.Cancelled)
                    {
                        <span class="badge badge-secondary">Cancelled</span>
                    }
                    else if (item.Approved == true)
                    {
                        <span class="badge badge-success">Approved</span>
                    }
                    else if (item.Approved == false)
                    {
                        <span class="badge badge-danger">Rejected</span>
                    }
                    else
                    {
                        <span class="badge badge-warning">Pending Approval</span>
                    }
                </td>
                <td>
                    @if (!item.Cancelled)
                    {
                        <a class="btn btn-outline-primary" asp-action="Details" asp-route-id="@item.Id">
                            <i class="fa fa-file"></i>Review
                        </a>
                    }
                </td>
            </tr>
        }
    </tbody>
</table>

@section Scripts{
    <!-- Your existing script section -->
    <script>
        $(document).ready(function () {
            var table = $('#mytable').dataTable();

            $('#exportButton').click(function () {
                // Get all rows from table
                var rows = $('#mytable tbody tr');
                var csvContent = "data:text/csv;charset=utf-8,";

                // Add table headers to CSV
                var header = [];
                $('#mytable th').each(function () {
                    header.push($(this).text().replace(/[\r\n]+/g, ''));
                });
                header.pop(); // Remove the last column header
                csvContent += header.join(",") + "\r\n";

                // Add table data to CSV
                rows.each(function () {
                    var rowData = [];
                    $(this).find('td').each(function (index) {
                        if (index !== 7) { // Exclude the last column
                            rowData.push($(this).text().replace(/[\r\n]+/g, ''));
                        }
                    });
                    csvContent += rowData.join(",") + "\r\n";
                });

                // Create a download link and click it to start downloading
                var encodedUri = encodeURI(csvContent);
                var link = document.createElement("a");
                link.setAttribute("href", encodedUri);
                link.setAttribute("download", "leave_requests.csv");
                document.body.appendChild(link);
                link.click();
            });

            function getQueryParameter(name) { 
                const urlParams = new URLSearchParams(window.location.search);
                return urlParams.get(name);
            }

            // Check if there's a 'filter' query parameter and set the value accordingly
            const searchValue = getQueryParameter("filter");

            if (searchValue) {
                // Set the search input value
                var searchInput = $('#mytable_filter input');
                searchInput.val(searchValue);

                searchInput.trigger($.Event('keyup', { keyCode: 13 }));
            }

            
        });
    </script>
}

Views/LeaveRequests/MyLeave.cshtml
@model EmployeeLeaveRequestVm
@using Microsoft.AspNetCore.Identity
@using Leave_Management.Data
@inject SignInManager<Employee> SignInManager
@inject UserManager<Employee> UserManager

@{
    ViewData["Title"] = "MyLeave";

}


    

<h1>My Leave Allocations</h1>

<div class="jumbotron mx-auto">
    <div class="card">
        <div class="table-responsive">
            <table class="table rounded">
                <thead>
                    <tr>
                        <th scope="col">Leave Type</th>
                        <th scope="col">Number of Days</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model.LeaveAllocations)
                    {
                        <tr>
                            <td>@item.LeaveType.Name</td>
                            <td><span class="badge badge-secondary">@item.NumberOfDays</span></td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

<h1>My Leave Records</h1>
<table class="table" id="tbldata">
    <thead>
        <tr>
            <th>
                Leave Type
            </th>
            <th>
                Total Days
            </th>
            <th>
                Start Date
            </th>
            <th>
                End Date
            </th>
            <th>
                Date Requested
            </th>
            <th>
                Approval Status
            </th>
            <th>
                Cancel Request
            </th>
          @*   <th>
                Rejection Reason
            </th> *@
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.LeaveRequests)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.LeaveType.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TotalDays)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.StartDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EndDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DateRequested)
                </td>
                <td>
                    @if (item.Cancelled)
                    {
                        <span class="badge badge-secondary">Cancelled</span>
                    }
                    else if (item.Approved == false)
                    {

                        <span class="badge badge-danger">Rejected</span>

                    }
                    else if (item.Approved == null)
                    {
                        <span class="badge badge-warning">Pending</span>

                    }
                    else
                    {
                        <span class="badge badge-success">Approved</span>
                    }
                </td>
                <td>
                    @if (!item.Cancelled && item.StartDate.Date >= DateTime.Now.Date && item.Approved == null)
                    {
                        <a asp-action="CancelRequest" class="btn btn-danger" asp-route-id="@item.Id" onclick="return confirm('Are you sure you want to Cancel?')">
                            <i class="fas fa-trash-alt"></i>
                        </a>
                    }
                </td>
                @* <td>
                    @if (item.Approved == false)
                    {
                        @Html.DisplayFor(modelItem => item.RejectionMessage)

                    }
                </td> *@
            </tr>
        }
    </tbody>
</table>
<br />
<br />
<br />
<br />


@section Scripts{
    <script>
        $(document).ready(function () {
            var table = $('#tbldata').DataTable();

            function getQueryParameter(name) {
                const urlParams = new URLSearchParams(window.location.search);
                return urlParams.get(name);
            }

            // Check if there's a 'filter' query parameter and set the value accordingly
            const searchValue = getQueryParameter("filter");

            if (searchValue) {
                // Set the search input value
                var searchInput = $('#tbldata_filter input');
                searchInput.val(searchValue);

                searchInput.trigger($.Event('keyup', { keyCode: 13 }));
            }
        });
    </script>
} 

Views/LeaveRequests/RejectionMessage.cshtml
@model Leave_Management.Models.LeaveRequestVm


<form asp-controller="LeaveRequests" asp-action="RMPost" asp-route-id="@Model.Id" method="post" class="needs-validation"  novalidate>
    <div class="form-group">
        <label for="rejectionMessage">Rejection Message:</label>
        <textarea class="form-control" id="rejectionMessage" name="rejectionMessage" rows="3"></textarea>
    </div>
    <button type="submit" class="btn btn-danger">Reject</button>
</form>

Views/LeaveRequests/Upsert.cshtml
@model Leave_Management.Models.CreateLeaveRequestVm

@{
    ViewData["Title"] = "Upsert";
}

<h1 class="text-center">Apply For Leave</h1>
<div class="d-flex justify-content-center">

    <hr class="w-25" />
</div>
<div class="row justify-content-center">
    <div class="col-md-7 col-lg-5">
        <form asp-action="Upsert">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="LeaveTypeId" class="control-label"></label>
                @Html.DropDownListFor(x => x.LeaveTypeId, new SelectList(Model.LeaveTypes, "Value", "Text"), "Select Leave Type", new { @class = "form-control" })
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="StartDate" class="control-label"></label>
                        <input asp-for="StartDate" class="form-control datetime" autocomplete="off"/>
                        <span asp-validation-for="StartDate" class="text-danger"></span>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label asp-for="EndDate" class="control-label"></label>
                        <input asp-for="EndDate" class="form-control datetime" autocomplete="off"/>
                        <span asp-validation-for="EndDate" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="RequestComments" class="control-label"></label>
                <textarea asp-for="RequestComments" class="form-control"></textarea>
                <span asp-validation-for="RequestComments" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Request Leave" class="btn btn-primary" />
            </div>
        </form>
        <div>
            <a class="btn btn-outline-secondary" asp-action="MyLeave" asp-controller="LeaveRequests">Back to List</a>
        </div>
    </div>
</div>


@section Scripts
{
    <script teyp="text/javascript">
        $(function () {
            $('.datetime').datepicker({
                dateFormat: 'yy-mm-dd', // Set the desired date format
                changeMonth: true, // Enable month dropdown
                changeYear: true, // Enable year dropdown
                minDate: 0 // Set the minimum selectable date to today
            });
        });
    </script>
}