Controllers/LeaveAllocationsController.cs
using AutoMapper;
using Leave_Management.Contracts;
using Leave_Management.Data;
using Leave_Management.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.UI.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.WebUtilities;
using Microsoft.CodeAnalysis;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Mail;
using System.Net;
using System.Threading.Tasks;
using Microsoft.AspNetCore.WebUtilities;
using System.Text.Encodings.Web;
using System.Text;

namespace Leave_Management.Controllers
{
    [Authorize(Roles = "Administrator, Manager")]
    public class LeaveAllocationsController : Controller
    {
        private readonly IUnitOfWork _uow;
        private readonly UserManager<Employee> _userManager;
        private readonly RoleManager<UserRole> _roleManager;
        private readonly IMapper _mapper;
        private readonly IEmailSender _emailSender;
        



        public LeaveAllocationsController(IEmailSender emailSender, IUnitOfWork uow, UserManager<Employee> userManager, IMapper mapper, RoleManager<UserRole> roleManager)
        {
            // _flashMessage = flashMessage;
            _uow = uow;
            _userManager = userManager;
            _mapper = mapper;
            _roleManager = roleManager;
            _emailSender = emailSender;
        }
        // GET: LeaveAllocation
        public IActionResult Index()
        {
            var leaveType = _uow.LeaveType.GetAll().ToList();
            var mappsLeaveTypeVms = _mapper.Map<List<LeaveType>, List<LeaveTypeVM>>(leaveType);
            var model = new CreateLeaveAllocationVM
            {
                NumberUpdated = 0,
                LeaveTypes = mappsLeaveTypeVms
            };
            return View(model);
        }
        #region API Calls

        //public async Task<IActionResult> GetAll()
        //{
        //    var allRoles = _roleManager.Roles.ToList();
        //    List<Employee> emps = new List<Employee>();

        //    foreach (var role in allRoles)
        //    {
        //        var usersInRole = await _userManager.GetUsersInRoleAsync(role.Name);
        //        emps.AddRange(usersInRole);
        //    }

        //    var model = _mapper.Map<List<EmployeeVm>>(emps);
        //    Console.WriteLine(model);
        //    return Json(new { data = model });
        //}






        public async Task<IActionResult> GetAll()
        {
            var allRoles = _roleManager.Roles.ToList();
            var employeesWithRoles = new List<EmployeeVm>();

            foreach (var role in allRoles)
            {
                var usersInRole = await _userManager.GetUsersInRoleAsync(role.Name);
                var roleName = role.Name.ToLower(); // Assuming role names are plural

                var roleEmployees = _mapper.Map<List<EmployeeVm>>(usersInRole);
                roleEmployees.ForEach(e => e.Role = roleName);

                employeesWithRoles.AddRange(roleEmployees);
            }

            Console.WriteLine(employeesWithRoles);
            return Json(new { data = employeesWithRoles });
        }



        // GET: LeaveType/Delete/5
        [HttpDelete]
        public async Task<IActionResult> Delete(int id)
        {
            var leaveType = await _uow.LeaveType.Get(id);
            if (leaveType == null)
                return Json(new { success = false, message = "Data Not Found!" });
            _uow.LeaveType.Delete(leaveType);
            _uow.Save();
            return Json(new { success = true, message = "Delete Operation Successfully" });
        }
        #endregion

        // GET: LeaveAllocation/Details/5
        public IActionResult Details(string id)
        {
            var employees = _mapper.Map<EmployeeVm>(_userManager.FindByIdAsync(id).Result);
            var allocations =
                _mapper.Map<List<LeaveAllocationVm>>(_uow.LeaveAllocation.GetAll(includeProperties: "LeaveType").Where(x => x.EmployeeId == id && x.Period == DateTime.Now.Year)
                    .ToList());
            var model = new ViewLeaveAllocationVM
            {
                Employee = employees,
                LeaveAllocationVms = allocations
            };

            return View(model);
        }

        // GET: LeaveAllocation/Create
        public async Task<ActionResult> SetLeave(int id)
        {
            var leaveTypes = await _uow.LeaveType.Get(id);
            var employees = _userManager.GetUsersInRoleAsync("Employee").Result;
            var managers = _userManager.GetUsersInRoleAsync("Manager").Result;

            var employeesAndManagers = employees.Concat(managers);

            foreach (var emp in employeesAndManagers)
            {
                if (_uow.LeaveAllocation.CheckAllocation(id, emp.Id))
                    continue;
                var allocation = new LeaveAllocationVm
                {
                    DateCreated = DateTime.Now,
                    EmployeeId = emp.Id,
                    LeaveTypeId = id,
                    NumberOfDays = leaveTypes.DefaultDays,
                    Period = DateTime.Now.Year
                };
                var leaveAllocation = _mapper.Map<LeaveAllocation>(allocation);
                _uow.LeaveAllocation.Create(leaveAllocation);
                _uow.Save();
            }

            return RedirectToAction(nameof(Index));
        }

        public IActionResult ListEmployee()
        {
            return View();
        }

        


        
        public IActionResult CreateEmployee()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator, Manager")]
        public async Task<IActionResult> CreateEmployee(EmployeeVm model)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View(model);
                }
                string password = "Maxval" + model.Firstname + "@123" + Guid.NewGuid().ToString();

                var user = new Employee
                {
                    Email = model.Email.ToLower(),
                    Firstname = model.Firstname,
                    Lastname = model.Lastname,
                    UserName = model.Email,
                    Discriminator = model.Discriminator
                };

                var result = await _userManager.CreateAsync(user, password);


                if (result.Succeeded)
                {
                    //TempData["Loading"] = "Laoding...";
                    _userManager.AddToRoleAsync(user, "Employee").Wait();
                    
                    //TempData["SuccessMessage"] = "Manager assigned successfully.";
                    
                    var code = await _userManager.GenerateEmailConfirmationTokenAsync(user);
                    code = WebEncoders.Base64UrlEncode(Encoding.UTF8.GetBytes(code));

                    // Construct the callback URL for email confirmation
                    var callbackUrl = Url.Action("ResetPassword", "Account", new
                    {
                        area = "Identity",
                        userId = user.Id,
                        code = code
                    }, Request.Scheme);

                    // Send confirmation email
                    await _emailSender.SendEmailAsync(model.Email, "Password for your account.", "Your password is " + password);

                    // Construct the return URL for password reset
                    var resetPasswordUrl = Url.Action("ResetPassword", "Account", new
                    {
                        area = "Identity",
                        Code = code,
                        returnUrl = "/Account/Login" // Redirect to login page after password reset
                    }, Request.Scheme);

                    // Redirect to list employee page after successful registration
                    return RedirectToAction(nameof(ListEmployee));

                }

                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError(string.Empty, error.Description);
                }

                // Return the view with model in case of validation errors
                return View(model);
            }
            catch (Exception ex)
            {
                // Log and handle the exception
                return View(model);
            }
        }






        public async Task<IActionResult> EmployeeRoles()
        {
            var users = _userManager.Users.ToList();
            var userVmList = _mapper.Map<List<EmployeeVm>>(users);



            return View(userVmList);
        }

        [HttpGet]
        public IActionResult GetAllRoles()
        {
            var allRoles = _roleManager.Roles.Select(r => r.Name).ToList();
            return Json(allRoles);
        }





        // POST: LeaveAllocations/AssignRole
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EmployeeRoles(string employeeId, string role)
        {
            var user = await _userManager.FindByIdAsync(employeeId);
            if (user == null || employeeId == "Please select a user.")
            {
                // ModelState.AddModelError("User", "User is not selected, Please select a user.");
                TempData["ErrorMessage"] = "User is not selected, Please select a user.";
                //_flashMessage.Warning("User is not selected, Please select a user.");
                return RedirectToAction(nameof(EmployeeRoles));
            }

            // Remove existing roles
            var userRoles = await _userManager.GetRolesAsync(user);
            await _userManager.RemoveFromRolesAsync(user, userRoles);


            var result = await _userManager.AddToRoleAsync(user, role);
            if (result.Succeeded)
            {

Controllers/LeaveTypesController.cs
using AutoMapper;
using Leave_Management.Contracts;
using Leave_Management.Data;
using Leave_Management.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Leave_Management.Controllers
{
    [Authorize(Roles = "Administrator, Manager")]
    public class LeaveTypesController : Controller
    {
        private readonly IUnitOfWork _uow;
        private readonly IMapper _mapper;

        public LeaveTypesController(IUnitOfWork uow, IMapper mapper)
        {
            _uow = uow;
            _mapper = mapper;
        }

        #region API Calls

        public IActionResult GetAll()
        {
            var leaveType = _uow.LeaveType.GetAll().ToList();
            var model = _mapper.Map<List<LeaveType>, List<LeaveTypeVM>>(leaveType);
            return Json(new { data = model });
        }

        // GET: LeaveType/Delete/5
        [HttpDelete]
        public async Task<IActionResult> Delete(int id)
        {
            var dataLeaveType = await _uow.LeaveType.Get(id);
            if (dataLeaveType == null)
                return Json(new { success = false, message = "Data Not Found!" });
            _uow.LeaveType.Delete(dataLeaveType);
            _uow.Save();
            return Json(new { success = true, message = "Delete Operation Successfully" });
        }
        #endregion

        // GET: LeaveType
        public ActionResult Index()
        {
            return View();
        }

        // GET: LeaveType/Details/5
        public async Task<IActionResult> Details(int id)
        {
            var model = await _uow.LeaveType.GetFirstOrDefault(u => u.Id == id);
            if (model == null)
            {
                return NotFound();
            }

            var models = _mapper.Map<LeaveTypeVM>(model);

            return View(models);
        }

        // GET: LeaveType
        public async Task<IActionResult> Create(int? id)
        {
            if (id == null)
            {
                //Create
                return View(new LeaveTypeVM());
            }
            //Update

            var model = await _uow.LeaveType.GetFirstOrDefault(u => u.Id == id);
            var leaveTypeVm = _mapper.Map<LeaveTypeVM>(model);

            if (leaveTypeVm == null)
            {
                return NotFound();
            }
            return View(leaveTypeVm);
        }

        // POST: LeaveType/Create/Update
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(LeaveTypeVM model)
        {
            try
            {
                if (!ModelState.IsValid)
                {
                    return View(model);
                }

                if (model.Id == 0) //Create
                {
                    TempData["result"] = "Create";
                    var leaveType = _mapper.Map<LeaveType>(model);
                    leaveType.DateCreated = DateTime.Now;
                    _uow.LeaveType.Create(leaveType);
                }
                else // Update
                {
                    TempData["result"] = "Update";
                    var leaveType = _mapper.Map<LeaveType>(model);
                    _uow.LeaveType.Update(leaveType);
                }
                _uow.Save();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View(model);
            }
        }


    //     public IActionResult DownloadLeaveTypes()
    //{
    //    var leaveTypes = _uow.LeaveType.GetAll(); // Retrieve all leave types from the database

    //    // Create a new Excel package
    //    using (var package = new ExcelPackage())
    //    {
    //        var worksheet = package.Workbook.Worksheets.Add("Leave Types"); // Create a worksheet

    //        // Add column headers
    //        worksheet.Cells["A1"].Value = "Leave Type Name";
    //        worksheet.Cells["B1"].Value = "Description";
    //        worksheet.Cells["C1"].Value = "Number of Days";

    //        // Populate data rows
    //        int row = 2;
    //        foreach (var leaveType in leaveTypes)
    //        {
    //            worksheet.Cells["A" + row].Value = leaveType.Name;
    //            zzworksheet.Cells["B" + row].Value = leaveType.Description;
    //            worksheet.Cells["C" + row].Value = leaveType.NumberOfDays;
    //            row++;
    //        }

    //        // Convert the Excel package to a byte array
    //        byte[] excelData = package.GetAsByteArray();

    //        // Return the Excel file as a downloadable file
    //        return File(excelData, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "LeaveTypes.xlsx");
    //    }
    //}






    }
}

Views/LeaveAllocations/AssignManager.cshtml
@if (TempData["SuccessMessage"] != null)
{
    <div class="alert alert-success" role="alert">
        @TempData["SuccessMessage"]
    </div>
}

@if (TempData["ErrorMessage"] != null)
{
    <div class="alert alert-danger" role="alert">
        @TempData["ErrorMessage"]
    </div>

}

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <h1 class="text-center">Assign Manager to Employee</h1>
            <form asp-action="AssignManager" method="post">
                <div class="form-group">
                    <label for="employee">Select Employee:</label>
                    <select class="form-control" name="employeeId" id="employee">
                        <option value="">-- Select Employee --</option>
                        @foreach (var employee in Model.Employees)
                        {
                            <option value="@employee.Id">@employee.Firstname  @employee.Lastname  </option>
                        }
                    </select>
                </div>
                <div class="form-group">
                    <label for="manager">Select Manager:</label>
                    <select class="form-control" name="managerId" id="manager">
                        <option value="">-- Select Manager --</option>
                        @foreach (var manager in Model.Managers)
                        {
                            <option value="@manager.Id">@manager.Firstname  @manager.Lastname</option>
                        }
                    </select>
                </div>
                <button type="submit" class="btn btn-primary btn-block">Assign Manager</button>
            </form>
        </div>
    </div>
</div>

Views/LeaveAllocations/CreateEmployee.cshtml
@model Leave_Management.Models.EmployeeVm

@{
    ViewData["Title"] = "Create Employee";
}

<h1 class="text-center">Create Employee</h1>
<hr />



<div class="row">
    <div class="col-md-4 mx-auto p-5">
        <form asp-action="CreateEmployee" method="post" id="createEmployeeForm">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            

            <div class="form-group">
                <label asp-for="Firstname" class="control-label"></label>
                <input type="text" asp-for="Firstname" class="form-control" />
                <span asp-validation-for="Firstname" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Lastname" class="control-label"></label>
                <input type="text" asp-for="Lastname" class="form-control" />
                <span asp-validation-for="Lastname" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input type="email" asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
               
                <input asp-for="Discriminator" class="form-control" value="Employee" type="hidden"/>
                <span asp-validation-for="Discriminator" class="text-danger"></span>
            </div>
                <input asp-for="UserName" class="form-control" type="hidden" />

            <div class="form-group">
                <button id="createEmployeeBtn" type="submit" class="btn btn-success">Create</button>
                <a asp-action="ListEmployee" class="btn btn-outline-primary">Back to List</a>
            </div>
        </form>
    </div>
</div>


@section Scripts {
<script>
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    </script>
}

Views/LeaveAllocations/Details.cshtml
@model Leave_Management.Models.ViewLeaveAllocationVM

@{
    ViewData["Title"] = "Details";
}

<div class="container">
    <h1 class="text-center display-6">Details For @Model.Employee.Firstname @Model.Employee.Lastname</h1>
    <hr />
    <div class="table-responsive">
        <table class="table table-bordered table-striped">
            <tbody>
                <tr>
                    <th class="text-center">Username:</th>
                    <td>@Html.DisplayFor(model => model.Employee.UserName)</td>
                </tr>
                <tr>
                    <th class="text-center">Email:</th>
                    <td>@Html.DisplayFor(model => model.Employee.Email)</td>
                </tr>
                <tr>
                    <th class="text-center">First Name:</th>
                    <td>@Html.DisplayFor(model => model.Employee.Firstname)</td>
                </tr>
                <tr>
                    <th class="text-center">Last Name:</th>
                    <td>@Html.DisplayFor(model => model.Employee.Lastname)</td>
                </tr>
             
               
            </tbody>
        </table>
    </div>
</div>

<hr />

@if (Model.LeaveAllocationVms.Any())
{
    <h2 class="text-center display-6">Leave Allocations</h2>
    <div class="table-responsive container text-center">
        <table class="table">
            <thead>
                <tr>
                    <th>Leave Type</th>
                    <th>Number of Days</th>
                    <th>Edit</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.LeaveAllocationVms)
                {
                    <tr>
                        <td>@item.LeaveType.Name</td>
                        <td><span class="badge badge-secondary">@item.NumberOfDays</span></td>
                        <td>
                            <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-outline-primary"><i class="fas fa-edit"></i> Edit</a>
                        </td>
                    </tr>
                }
            </tbody>

        </table>
            <a class="btn btn-outline-secondary" asp-action="ListEmployee">Back to List</a>
    </div>
}

Views/LeaveAllocations/Edit.cshtml
@model Leave_Management.Models.EditLeaveAllocationVM

@{
    ViewData["Title"] = "Edit";
}

<h1 class="text-center mt-3">Editing @Model.LeaveType.Name Allocation for @Model.Employee.Firstname @Model.Employee.Lastname</h1>
<div class="d-flex justify-content-center">

    <hr class="w-25" />
</div>
<div class="row">
    <div class="col-md-4 mx-auto ">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <input type="hidden" asp-for="EmployeeId" />
            <div class="form-group">
                <label asp-for="NumberOfDays" class="control-label"></label>
                <input asp-for="NumberOfDays" class="form-control" />
                <span asp-validation-for="NumberOfDays" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
        <div>
            <a class="btn btn-outline-secondary" asp-controller="LeaveAllocations" asp-action="ListEmployee">Back to List</a>
        </div>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/LeaveAllocations/EditEmployee.cshtml
@model Leave_Management.Models.EmployeeVm

@{
    ViewData["Title"] = "Edit Employee";
}

<h1>Edit Employee</h1>
<hr />

<div class="row">
    <div class="col-md-6">
        <form asp-action="EditEmployee" method="post">
            <input type="hidden" asp-for="Id" />
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="Firstname" class="control-label"></label>
                <input asp-for="Firstname" class="form-control" />
                <span asp-validation-for="Firstname" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Lastname" class="control-label"></label>
                <input asp-for="Lastname" class="form-control" />
                <span asp-validation-for="Lastname" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="TaxId" class="control-label"></label>
                <input asp-for="TaxId" class="form-control" />
                <span asp-validation-for="TaxId" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="UserName" class="control-label"></label>
                <input asp-for="UserName" class="form-control" />
                <span asp-validation-for="UserName" class="text-danger"></span>
            </div>

            <div class="form-group">
                <button type="submit" class="btn btn-primary">Save Changes</button>
                <a asp-action="ListEmployee" class="btn btn-outline-primary">Back to List</a>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Views/LeaveAllocations/EmployeeRoles.cshtml
@model List<EmployeeVm>

@{
    ViewData["Title"] = "Assign Role";
}

@if (TempData["SuccessMessage"] != null)
{
    <div class="alert alert-success" role="alert">
        @TempData["SuccessMessage"]
    </div>
}

@if(TempData["ErrorMessage"] != null)
{
    <div class="alert alert-danger" role="alert">
        @TempData["ErrorMessage"]
    </div>

}

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <h1 class="text-center">Assign Role</h1>
            <form asp-controller="LeaveAllocations" asp-action="EmployeeRoles" method="post">
                <div class="form-group">
                    <label for="employeeId">Select Employee:</label>
                    <select class="form-control " id="employeeId" name="employeeId">
                        <option value="Please Select a user.">Please select a user.</option>
                        @foreach (var employee in Model)
                        {
                            <option value="@employee.Id">@employee.Firstname @employee.Lastname</option>
                        }
                    </select>
                </div>
                <div class="form-group">
                    <label for="role">Select Role:</label>
                    <select class="form-control " id="role" name="role">
                        <!-- Roles will be populated dynamically -->
                    </select>
                </div>
                <button type="submit" class="btn btn-primary btn-block">Assign Role</button>
            </form>
        </div>
    </div>
</div>


@* 
// If you want to make it a table use this code    
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <h1 class="text-center">Assign Role</h1>
            <form asp-controller="LeaveAllocations" asp-action="EmployeeRoles" method="post">
                <table class="table table-bordered">
                    <tr>
                        <th>Select Employee</th>
                        <td>
                            <select class="form-control form-control-sm" id="employeeId" name="employeeId">
                                @foreach (var employee in Model)
                                {
                                    <option value="@employee.Id">@employee.Firstname @employee.Lastname</option>
                                }
                            </select>
                        </td>
                    </tr>
                    <tr>
                        <th>Select Role</th>
                        <td>
                            <select class="form-control form-control-sm" id="role" name="role">
                                <!-- Roles will be populated dynamically -->
                            </select>
                        </td>
                    </tr>
                </table>
                <div class="text-center">
                    <button type="submit" class="btn btn-primary btn-sm">Assign Role</button>
                </div>
            </form>
        </div>
    </div>
</div>
 *@


@section Scripts {
    <script src="~/js/LeaveAllocation.js"></script>
    <script>
        $(document).ready(function () {
            // AJAX call to fetch roles dynamically
            $.ajax({
                url: "/LeaveAllocations/GetAllRoles",
                type: 'GET',
                success: function (data) {
                    // Populate roles dropdown
                    $.each(data, function (index, item) {
                        $('#role').append('<option value="' + item + '">' + item + '</option>');
                    });
                }
            });
        });
    </script>
}

Views/LeaveAllocations/Index.cshtml
@model Leave_Management.Models.CreateLeaveAllocationVM
@{
    ViewData["Title"] = "Index";
}
<div class="row">
    <div class="col-6">
        <h2 class="text-primary">Leave Allocations List </h2>
    </div>
    <div class="col-6 text-right">
        <a class="btn btn-success" asp-controller="LeaveTypes" asp-action="Create"><i class="fas fa-plus"></i> &nbsp; Create New Leave Type</a>
    </div>
</div>
<br />
<div class="p-4 border rounded">
    <table id="tblData" class="table table-striped table-bordered" style="width:100%">
        <thead class="thead-dark">
            <tr class="table-info">
                <th>
                    Leave Types
                </th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.LeaveTypes)
            {
                <tr>
                    <td>@item.Name</td>
                    <td>
                        <a asp-action="SetLeave" asp-route-id="@item.Id" class="btn btn-outline-success"><i class="fas fa-edit"></i>Allocate To Employee</a>
                        <!--Html.ActionLink("Allocate To You", "SetLeave", new {item.Id})-->
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

@section Scripts{
    <script>
        $(function () {
            var save = '@TempData["result"]';
            if (save != null && save != '') {
                if (save == "Update") {
                    toastr.info('Update Operation Successfully');
                }
                else toastr.success('Successfully Created Leave Type');
            }

        })
    </script>
}

Views/LeaveAllocations/ListEmployee.cshtml
@{
    ViewData["Title"] = "Index";
}
<div class="row">
    <div class="col-6">
        <h2 class="text-primary">List Of Employee </h2>
    </div>
    
    <div class="col-6 text-right">
        
        <a class="btn btn-success" asp-controller="LeaveAllocations" asp-action="CreateEmployee"><i class="fas fa-plus"></i> &nbsp; Create New Employee</a>
        
    </div>
</div>
<br />
<div class="p-4 border rounded">
    <table id="tblData" class="table table-striped table-bordered" style="width:100%">
        <thead class="thead-dark">
            <tr class="table-info">
                <th>
                    First Name
                </th>
                <th>
                    Last Name
                </th>
                <th>
                    Email
                </th>
                <th>
                    Role
                </th>
                <th>
                    AssignedManager
                </th>
                
                
               
                <th>Action</th>
               
                

                
            </tr>
        </thead>

    </table>
</div>

@section Scripts{
    <script src="~/js/LeaveAllocation.js"></script>
    <script>
        $(function () {
            var save = '@TempData["result"]';
            if (save != null && save != '') {
                if (save == "Update") {
                    toastr.info('Update Operation Successfully');
                }
                else toastr.success('Successfully Created Leave Type');
            }

        })






    </script>


    
}